version: "3"

services:
  server:
    build: ./intro_server
    ports:
      - 9000:9000
    environment:
      - OFFLINE_TABLE=1
      - PORT=9000

  db:
    image: mongo:4
    ports:
      - 27017:27017
    command: mongod --smallfiles
