version: "3"

services:
  server:
    build: https://github.com/levgou/table-handler.git#master:intro_server
    ports:
      - 9000:9000
    environment:
      - OFFLINE_TABLE=1
      - PORT=9000
    # volumes:
    # - ./intro_server:/app-src


  db:
    image: mongo:4
    ports:
      - 27017:27017
    command: mongod --smallfiles
