/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData beer = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cake = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData local_bar = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData wine = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData keyboard_arrow_down = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData gift = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData qrcode = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData fast_food = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData restaurant = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData coffee = const IconData(0xf0f4, fontFamily: _kFontFam);
}
